import React from 'react';
import AppLayout from '../components/layout/AppLayout';

function DisclaimersPage() {
  return (
    <AppLayout>
      <main className="container pb-20 pt-10 max-w-3xl mx-auto px-6">
        <h2
          className="text-3xl font-bold text-slate-900 mb-2"
          style={{ fontFamily: "'Space Grotesk', sans-serif" }}
        >
          Legal Disclaimers
        </h2>
        <p className="text-sm text-slate-500 mb-8">Please read before using this service.</p>

        <div className="space-y-6 text-sm text-slate-700 leading-relaxed">

          <section>
            <h3 className="font-semibold text-slate-900 mb-1">Not a Law Firm</h3>
            <p>
              DepositBack is not a law firm and does not provide legal advice. Use of this service
              does not create an attorney-client relationship. Nothing in this service or in any
              document generated by this service constitutes legal advice, legal counsel, or legal
              representation of any kind.
            </p>
          </section>

          <section>
            <h3 className="font-semibold text-slate-900 mb-1">Document Preparation Service Only</h3>
            <p>
              DepositBack is a document preparation and informational service. We help you organize
              your facts, understand publicly available Texas rules, and generate professionally
              formatted documents based on information you provide. We do not apply law to your
              specific facts, recommend legal strategy, or predict outcomes.
            </p>
          </section>

          <section>
            <h3 className="font-semibold text-slate-900 mb-1">Texas Residential Leases Only</h3>
            <p>
              This service is designed exclusively for Texas residential lease disputes. It is not
              suitable for commercial leases, leases in other states, federal claims, or roommate
              disputes not involving a landlord. If your situation involves any of these, please
              consult a licensed attorney in the applicable jurisdiction.
            </p>
          </section>

          <section>
            <h3 className="font-semibold text-slate-900 mb-1">No Outcome Guaranteed</h3>
            <p>
              Use of this service does not guarantee any particular outcome. The information and
              documents generated by this service are based solely on the facts you provide and on
              publicly available information about Texas law. Individual results will vary. DepositBack
              makes no representation that any document generated will result in the return of a
              security deposit or any other specific outcome.
            </p>
          </section>

          <section>
            <h3 className="font-semibold text-slate-900 mb-1">Consult a Licensed Attorney</h3>
            <p>
              If you have questions about your legal rights, need representation, or are considering
              court action, you should consult a licensed Texas attorney. Texas lawyers may be found
              through the{' '}
              <a
                href="https://www.texasbar.com/AM/Template.cfm?Section=Lawyer_Referral_Service"
                className="text-blue-600 underline hover:text-blue-800"
                target="_blank"
                rel="noopener noreferrer"
              >
                State Bar of Texas Lawyer Referral Service
              </a>
              . Many offer free or low-cost initial consultations.
            </p>
          </section>

          <section>
            <h3 className="font-semibold text-slate-900 mb-1">Accuracy of Information</h3>
            <p>
              While we strive to reference publicly available Texas law accurately, laws change and
              the information in this service may not reflect recent legislative updates, court
              decisions, or local ordinances. Always verify any information with a licensed attorney
              before taking legal action.
            </p>
          </section>

          <section>
            <h3 className="font-semibold text-slate-900 mb-1">Refund Policy</h3>
            <p>
              Because documents are generated immediately upon payment, refunds are generally not
              available once a document has been delivered. If you experience a technical failure
              that prevented delivery, contact us for assistance. Refund eligibility is not affected
              by the outcome of your dispute.
            </p>
          </section>

        </div>
      </main>
    </AppLayout>
  );
}

export default DisclaimersPage;
